nelmio_api_doc:
    documentation:
        info:
            title: My App
            description: This is an awesome app!
            version: 1.0.0
        components:
            securitySchemes:
                ApiKeyAuth: # arbitrary name for the security scheme
                    type: apiKey
                    in: header       # can be "header", "query" or "cookie"
                    name: X-API-KEY
            schemas:
                ResetPasswordRequest:
                    type: object
                    properties:
                        email:
                            type: string
        security:
            -   ApiKeyAuth: [ ]
    areas: # to filter documented areas
        path_patterns:
                - ^/api/(?!doc).* # Accepts routes under /api except /api/doc
